### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by SenorTroubadour** [dubtrack/www-dubtrack-fm#151]
Since SukaNekoto doesn't think the dubtrack dev reads the dubtrck subreddit I am linking the Feature Request post here.

https://www.reddit.com/r/dubtrack/comments/3rpwmx/feature_requests/

**Comment by RobGoldy** [comment]
While I agree posting this here is a great idea,I find it a little harsh to call out SukaNekoto and put words in his mouth....

**Comment by thedark1337** [comment]
https://www.reddit.com/r/dubtrack/comments/3rpwmx/feature_requests/cwqbx7e

Not putting words in anyone's mouth lol. Direct quote: We don't know how often the developers of dubtrack are looking at this subreddit

**Comment by RobGoldy** [comment]
"We don't know how often the developers of dubtrack are looking at this subreddit" does not mean "doesn't think the dubtrack dev reads the dubtrck subreddit"

Regardless, I still feel it is harsh and uncalled for to call someone out like that. Especially when it really is irrelevant to this ticket. Instead of calling him out, we should be discussing the features, which ones are feasible and how to implement them!

**Comment by SenorTroubadour** [comment]
SukaNekoto specifically told me to post here because he doesn't not think the dev's read the dubtrack subreddit, which is of course, not true. If you think it's harsh for someone to hold you accountable for thing you say, life will be tough for you.

**Comment by RobGoldy** [comment]
Again @SenorTroubadour regardless of whether or not it was harsh or called for, it is still irrelevant to this ticket.

How should we move forward with these suggestions? A lot of them make sense but also a lot of them have already been posted previously. Should we try to separate the suggestions that are actually feasible and open them as separate tickets so that we can address them in an orderly fashion?

**Comment by SenorTroubadour** [comment]
@RobGoldy i really don't care how you move forward as I never wanted to post to this board but did so as advised by SukaNekoto. I know the reddit thread has been read by the appropriate people so delete this for all I care.
