### ISSUE TITLE
[Feature Request] Spotify Songs

### ISSUE THREAD

**Issue by RobGoldy** [dubtrack/www-dubtrack-fm#168]
Would it be possible to implement Spotify as a source for songs? I've seen that it is possible to play and embed songs from Spotify's Web Player within Facebook so I feel that this may already be possible. I looked into their web API and it seems that it is possible but would require everyone to press the play button instead of autoplaying (maybe we could automate that process to get it to autoplay). Still, I think this is worth bringing up and at worst we can look into the future when this may be fully possible.

**Comment by RobGoldy** [comment]
Actually I looked more into this and it appears that the web player widgets and embeds only act as a remote control for the web player :( Does not look like this will be possible yet but when it does become possible it could be an amazing feature.

**Comment by coryshaw1** [comment]
From Spotify's API Documentation:

> ## Is there a JS SDK for the player? Can I send play/pause commands using Javascript?
> 
> The Play button doesn’t have any observable events, nor does it listen for any. Playback can only be triggered by the user clicking the button.
> We’re certainly looking at creating a JS SDK; it’s a bigger project and right now we’re focusing on quickly releasing APIs to open up the general Spotify ecosystem (catalogue, playlists, etc).
> None of these requests are falling on deaf ears, and we’re working hard to bring out as much functionality as we can.
> 
> ## Autoplay
> 
> Is there an auto-play option on the widget?
> No, there is not. The user has to start playback by clicking on the Play Button, which will open the web player or desktop client to start the playback.

No JS events to bind to. 
No legitimate way to autoplay (may even go against ToS if we try to force autoplay).

I may be wrong in saying it's not possible since I haven't really tried to do it myself, but it looks near impossible at this point in time. Maybe once they update with a JS SDK we can have more control over it.

EDIT: Yeah, testing out their "Play Button" just opened up my Spotify app on OSX. And I guess their "Web Player" means redirect to their web app. May have to hold off on this one.

**Comment by seatsea** [comment]
The issue is that afaik, even if it was doable, it would require all
listeners to have a Spotify account.
