### ISSUE TITLE
'Uncaught TypeError: Cannot read property 'scollBottomChat' of undefined'

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#179]
loading rooms in chrome is all messed up due to this typo. scrolling is messed up in IE. please fix :)

**Comment by nambok** [comment]
can you try again? clear cache :)

**Comment by rstuckless** [comment]
hey nambok! so a bunch of us are getting the same issue on all different browsers/OSs. It seems to resolve itself if I do a hard refresh/ipflush, but then will come back intermittently if i do the same again. Is there a chance that maybe one of the webservers is out of synch and the load balancer doesnt recognize it? I checked and it doesnt look like there have been commits, but I know you were having issues yesterday so maybe it was a buggy deploy or something? The issue is persistent and is not cache related so far as I can tell.

**Comment by nambok** [comment]
@rstuckless just pushed and update can you try again?

**Comment by chrisrohn** [comment]
seems to have fixed it for me.

**Comment by nambok** [comment]
ok cool closing this now
