### ISSUE TITLE
[BUG] Chat goes "to the infinity and beyond" when typing multiple lines without anyone else talking

### ISSUE THREAD

**Issue by netux** [dubtrack/www-dubtrack-fm#181]
![Image showing the problem](https://i.gyazo.com/ede881d4ed5ba15c72c6f3e0f01d8c5b.png)

Scrolling up fixes the problem, but it's still annoying.

Notice I'm using DubX and a Custom CSS, but I've talked to other users who seem to have the same problem without DubX turned on.

**Comment by avatarkava** [comment]
Hey @Netox005 - Browser and rough dimensions of the window you're using?

**Comment by netux** [comment]
Browser: Chrome
Browser window size: 1440 x 775
Screen size: 1440 x 900

**Comment by Not-Kris** [comment]
This is due to the chat now being limited to the 1000 most recent messages. When new messages are "smaller" in height than the oldest message, the difference makes the chat scroll up, because now the total chat log is also "smaller" in height. 

This needs to be addressed by preventing the chat from being able to "scroll up" and leave blank space below it, without using `ScrollToBottom`, as this will prevent people from reading back in the chat when the chat is active.

**Comment by Larry1123** [comment]
Why not have a if the last li is view-able scrolltobottom ?

http://stackoverflow.com/a/488073 << see if element is able to be seen.
`$(".chat-main li:last-child")` << the selector that should give you the last li of the chat

I'm sure that someone that knows the code better would be able to do something with this info.

**Comment by netux** [comment]
I check now and it's fixed, thank you devs!
