### ISSUE TITLE
Queue tracks by direct media URL

### ISSUE THREAD

**Issue by ehedaya** [dubtrack/www-dubtrack-fm#197]
Unsure of how possible this is as I know very little about streaming audio, but if I upload a file to, say, my Dropbox or Amazon S3 bucket, and get a public URL for the audio file that I want to play in the room, could that be supported somehow?

**Comment by RobGoldy** [comment]
**EDITED RESPONSE**
Well it is possible but it would cause legal troubles. Your best bet it to
upload it to Soundcloud or Youtube. 

The moment Dubtrack starts supporting hosting audio would mean that it is illegally streaming the songs without giving money to the artists. The only reason Youtube / Soundcloud / iTunes / Pandora / Etc. are able to do this is because they have deals with the labels. If you hosted it on your own dropbox and started streaming it, you would personally be held liable for any lawsuits from artists/labels.

**Comment by ehedaya** [comment]
Understood. Thanks Rob!
