### ISSUE TITLE
scroll bar on the right side of the screen

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#24]
why is there a scroll bar on the right side of the screen?  it doesn't do anything and it is unpleasant to look at, especially in full screen.  please remove! thanks :)

**Comment by mxew** [comment]
Are you saying that you want the scroll bar to go away when the window is big enough to fit all of the content without scrolling? The fix for that would be setting `overflow-y: auto;`. 

However, users with smaller screens probably prefer `overflow-y: scroll;`. Some pages on dubtrack can fit on their screens without a scrollbar (like the users pages), and some can not (like the main room view). Switching back and forth between pages with and without scrollbars would cause a bit of a visual inconsistency.

**Comment by mortenn** [comment]
I would suggest putting the pages that do not fit in one page into an embedded div with an internal overflow, so that that list scrolls rather than the entire page.

**Comment by nambok** [comment]
this is now fixed on the new UI, closing this for now but feel free to re-open if issue persists
