### ISSUE TITLE
Users can run commands on themselves

### ISSUE THREAD

**Issue by coryshaw1** [dubtrack/www-dubtrack-fm#72]
Brought to attention by @JTBrinkmann

This includes kick, mute, ban, and others

**Comment by nambok** [comment]
@coryshaw1 haha we actually made this in purpose, it was more as a joke so if you did something stupid you could kick yourself. If enough people want this fix ill add it :)

**Comment by rklados** [comment]
I'm okay with this joke :)

**Comment by jtrutwin-zz** [comment]
I personally think it's great that you can /kick yourself.  I wouldn't change it.  Nice to know the devs have a sense of humor.  :)

**Comment by coryshaw1** [comment]
If it's intended, then fine by me! Hope you can't ban yourself from your own channel without any other mods though

**Comment by JTBrinkmann** [comment]
I think kicking yourself is quite fun, however banning, muting shouldn't be (I haven't tested it myself).
However, I think we should make sure to that bot developers are/become aware of this, so that bot scripts have a check to not accidentally kick themselves out (e.g. put a note in an API documentation, once we get [a serious] one)

**Comment by joedubtrack** [comment]
We are working on the mod roles atm so we can fix that before we push tonight

**Comment by jtrutwin-zz** [comment]
ahh, can you leave the /ban thyself tho?

**Comment by chrisrohn** [comment]
as a room creator i am not authorized to /kick myself. can this be added in?

**Comment by nambok** [comment]
this was fix with mod roles, closing this but feel free to re-open
